node {
    // Set up environment
    def appName = 'nodejs-app'
    def repoUrl = 'https://github.com/Jayrane03/Devops'
    def appDir = 'node-app'  // The folder where your app is located

    stage('Clone Repository') {
        git url: repoUrl, branch: 'master'
    }

    stage('Install Dependencies') {
        dir(appDir) {
            bat 'npm install'
        }
    }

    stage('Run Tests') {
        // If you have tests, you can run them here
        dir(appDir) {
            bat 'npm test'
        }
    }

    stage('Build') {
        // You can run build steps here if required
        echo 'Building the app'
    }

    stage('Deploy') {
        // For simplicity, deploying locally here
        dir(appDir) {
            bat 'npm start'
        }
    }

    // Post-build actions (cleanup, notifications, etc.)
    post {
        success {
            echo 'Build and Deploy successful!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
